### ISSUE TITLE
SMAPE implementation

### ISSUE THREAD

**Issue by AndresMR77** [Pieter-Cawood/FFORMA-ESRNN#1]
Hi, could you please explain the reason of adding epsilon, 0.5 and a max() function to SMAPE? 

I am trying to use smape as loss function for a personal project and would really like to understand your implementation.

Thanks!

```
def smape_loss(y_true, y_pred):
     epsilon = 0.35
     summ = K.maximum(K.abs(y_true) + K.abs(y_pred) + epsilon, 0.5 + epsilon)
     smape = K.abs(y_pred - y_true) / summ * 2.0
     return smape
```

**Comment by Pieter-Cawood** [comment]
added in the SMAPE implementation to handle edge cases and improve the stability of the calculation
